### ISSUE TITLE
AttributeError: 'LipidInteraction' object has no attribute 'r'

### ISSUE THREAD

**Issue by sefaheric** [wlsong/PyLipID#13]
I get AttributeError: 'LipidInteraction' object has no attribute 'r' when I go through the tutorial. The error points to line 259 as below. Is there something I might be doing wrong?

Thanks.
[hbht.pdf](https://github.com/wlsong/PyLipID/files/5994472/hbht.pdf)

**Comment by wlsong** [comment]
Sorry about this. I accidentally made a typo after the test. 
I've correct it and upload the v1.3.0.

Wanling

**Comment by sefaheric** [comment]
Thanks for the quick response. 

I encountered a new error, this time with the compute_surface_area module as in the attachment below:

[12.pdf](https://github.com/wlsong/PyLipID/files/5995874/12.pdf)

**Comment by wlsong** [comment]
Thanks. This is the bug I just fixed in v1.3.2...
Sorry that this package is still at early stage and not very stable... Thanks for your interests in our project :)

**Comment by sefaheric** [comment]
Thanks again, I really appreciate your quick response. I have generated a "show_binding_site_info.py" but unable to get pymol to run it. I get this error: "NameError: name 'column_id_residue_index' is not defined". Here are my .csv and my .gro files.
[Dataset_HBHT.csv.gz](https://github.com/wlsong/PyLipID/files/5997505/Dataset_HBHT.csv.gz)
[aa_charmm.gro.gz](https://github.com/wlsong/PyLipID/files/5997506/aa_charmm.gro.gz)
[show_binding_site_info.py.gz](https://github.com/wlsong/PyLipID/files/5997507/show_binding_site_info.py.gz)

**Comment by wlsong** [comment]
Hi ,
Can you try v1.3.3 to see if the bug got fixed?

**Comment by sefaheric** [comment]
I tried, the error however moved to the next line: 
"binding_site_identifiers.append(data_list[column_id_BS])".

Thanks.

**Comment by wlsong** [comment]
I think you were using the older version of pylipid based on the file generated. The latest one is v1.3.4 which can be checked on the github page. Sometimes 'pip' may not install the latest version, to make sure it does that, you can either specify the version when you are installing pylipid 'pip install pylipid=1.3.4' or delete your existing pylipid before installing the new one. 

Another thing I noticed is that you provide a 'gro' file which cannot be recognized. You need a 'pdb' file.

**Comment by sefaheric** [comment]
Thanks. I reinstalled v1.3.4 and tried my data again but pymol still complains about 'column_id_BS' not defined:

"NameError: name 'column_id_BS' is not defined".

When I comment out <elif column_name == "Binding site ID":>, in the pymol script, it runs, but of course puts all the BS at the same location.

**Comment by wlsong** [comment]
How odd is that..
Can you upload your pdf file, csv file and show_binding_site_info.py ?

**Comment by wlsong** [comment]
FYI, please use the csv file generated by this new pylipid as the column names are different from the file generated by the older version. I guess is that you may be using the older csv file. But this is just my guess.

**Comment by sefaheric** [comment]
I found that the instance of "Binding Site ID" in the pyMol script used a lower case "s", while the data file used an upper case "S". That was the cause of the issue. Thanks for your meticulous responses.

**Comment by wlsong** [comment]
Aha, thanks for pointing it out.
