### ISSUE TITLE
'pylipid' is not a package ERROR?

### ISSUE THREAD

**Issue by dimkol94** [wlsong/PyLipID#15]
Hi,

With the script provided in readthedocs and with pip install pylipid in my conda env 'pylipid-new', I get the following error

Exception has occurred: ModuleNotFoundError
No module named 'pylipid.api'; 'pylipid' is not a package
  File "/user/cg_new-prj/pylipid.py", line 6, in <module>
    from pylipid.api import LipidInteraction

Have you encountered this? The site packages are already in my sys.path anyway and pylipid is definetely installed since I can see it with conda list.

**Comment by wlsong** [comment]
Hi,

I've never seen this issue before. Maybe it is a permission issue. Could you try "pip3 install PyLipID --user" and see it works?

**Comment by dimkol94** [comment]
Same error I’m afraid.

Dimitris

********************
Dimitrios Kolokouris (M.Pharm honours)

DPhil in Structural Biology and Molecular Biophysics (Newstead & Biggin Groups)
Department of Biochemistry, University of Oxford

On 29 Mar 2021, at 18:32, Wanling Song ***@***.******@***.***>> wrote:

pip3 install PyLipID --user

**Comment by wlsong** [comment]
Without knowing how your python environment is setup, it's difficult to check what the issue is here. You may want to figure our the python environment first. 
Alternatively, you can download the source code from github and install the package by " python setup.py install".

**Comment by dimkol94** [comment]
Hi Wanling,

Typical sbcb modules loaded and then with cones I created a new environment and installed all dependencies coming with py lipids latest version. I have barely done anything else really, which is why this I puzzling.

Since we know each other maybe you can check up close on my computer tomorrow if you’re at the lab?

Would you be up for that?

Dimitris

********************
Dimitris Kolokouris (M.Pharm)
PhD candidate
Oxford Interdisciplinary Bioscience DTP (BBSRC scholarship)
University of Oxford
________________________________

**Comment by wlsong** [comment]
Okay. I am in the lab.

**Comment by dimkol94** [comment]
Hi Wanling,

As you may have overheard I had crashed my computer today so I needed to fix it. Luckily Michael was around to help out with the issue. This explains why I didn’t bother you with the previous error.

I will try again to run pylipid with the new installation, hopefully it will work since the previous “crashed” OS had permission problems which may have conflicted with pylipid.

Bestw wishes,
Dimitris

********************
Dimitrios Kolokouris (M.Pharm honours)

DPhil in Structural Biology and Molecular Biophysics (Newstead & Biggin Groups)
Department of Biochemistry, University of Oxford

On 30 Mar 2021, at 09:56, Wanling Song ***@***.******@***.***>> wrote:



Okay. I am in the lab.
