### ISSUE TITLE
Posonlyargs

### ISSUE THREAD

**Issue by Raksha166** [wlsong/PyLipID#17]
Dear Wanling, 

Thanks for Pylipid!

I am trying to use Pylipid 1.4.8. 

However, li.collect_residue_contacts() results in **TypeError: required field "posonlyargs" missing from arguments**

Here's the entire error:
TypeError                                 Traceback (most recent call last)
<ipython-input-11-6d68862f75c9> in <module>
----> 1 li.collect_residue_contacts()

~/anaconda3/lib/python3.8/site-packages/pylipid/api/api.py in collect_residue_contacts(self)
    290                                total=len(self._trajfile_list)):
    291             traj = md.load(self._trajfile_list[traj_idx], top=self._topfile_list[traj_idx], stride=self._stride)
--> 292             traj_info, self._protein_ref, self._lipid_ref = get_traj_info(traj, self._lipid,
    293                                                                           lipid_atoms=self._lipid_atoms,
    294                                                                           resi_offset=self._resi_offset,

~/anaconda3/lib/python3.8/site-packages/pylipid/util/trajectory.py in get_traj_info(traj, lipid, lipid_atoms, resi_offset, nprot, protein_ref, lipid_ref)
     58     """
     59     lipid_index_dict = defaultdict(list)
---> 60     lipid_atom_indices = traj.top.select("resn {}".format(lipid))
     61     if lipid_atoms is not None:
     62         for atom_index in lipid_atom_indices:

~/anaconda3/lib/python3.8/site-packages/mdtraj/core/topology.py in select(self, selection_string)
   1046         """
   1047 
-> 1048         filter_func = parse_selection(selection_string).expr
   1049         indices = np.array([a.index for a in self.atoms if filter_func(a)])
   1050         return indices

~/anaconda3/lib/python3.8/site-packages/mdtraj/core/selection.py in __call__(self, selection)
    398 
    399         expr = eval(
--> 400             compile(ast.fix_missing_locations(func), '<string>', mode='eval'),
    401             SELECTION_GLOBALS)
    402         return _ParsedSelection(expr, source, astnode)

I wonder what could be going wrong.

Thanks.

Edit - This issue is only python 3.7 or greater.

**Comment by wlsong** [comment]
Hi, Sorry for this late reply. I wonder if you check the mdtraj version. It seems that the issue has something to do with mdtraj.

**Comment by wlsong** [comment]
Also which python version you are using. 
I just saw a post reporting this issue with python 3.8.1, but it is fine with later version. 
https://stackoverflow.com/questions/59564990/typeerror-required-field-posonlyargs-missing-from-arguments-error-running-a-p
