### ISSUE TITLE
Plotting koff figure in the tutorial

### ISSUE THREAD

**Issue by andresilvapimentel** [wlsong/PyLipID#18]
I would like how to plot the two koff figures in the tutorial 0-application-walk-through. What is the command?

**Comment by andresilvapimentel** [comment]
After the plotting command, I have found the folowing error message:
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-5-2c1f19be6191> in <module>()
     77 li.compute_residue_koff(residue_id=None, plot_data=True, fig_close=True,
     78                         fig_format=fig_format, num_cpus=num_cpus)
---> 79 li.compute_binding_nodes(threshold=binding_site_size, print_data=False)
     80 if len(li.node_list) == 0:
     81     print("*"*50)

1 frames
/usr/local/lib/python3.7/dist-packages/pylipid/func/binding_site.py in get_node_list(corrcoef, threshold)
     86                                    # negative correlationsare are forced to separate to different binding sites.
     87     graph = nx.Graph(corrcoef)
---> 88     partition = community.best_partition(graph, weight='weight')
     89     values = [partition.get(node) for node in graph.nodes()]
     90     node_list = []

AttributeError: module 'community' has no attribute 'best_partition'

How to solve this issue?

**Comment by wlsong** [comment]
Hi,

Could you please let me know how you installed pylipid? If you installed pylipid via 'pip install pylipid', it shouldn't have an issue. 
Do you think this is relevant to the issue you reported here? https://stackoverflow.com/questions/53017174/attributeerror-module-networkx-algorithms-community-has-no-attribute-best-pa

If you have install pylipid properly, you should be able to go through the tutorials step by step, or run all of the analysis once via the script provided in 'Demo' (https://pylipid.readthedocs.io/en/master/demo.html)

**Comment by andresilvapimentel** [comment]
I installed it using pip install pylipid and it worked at the first day I
used. Then, in the following day, it stopped working in a very strange
manner.

Em qui, 22 de jul de 2021 10:35, Wanling Song ***@***.***>
escreveu:

**Comment by wlsong** [comment]
I don't understand why 'worked at the first day' then stopped working. 
It may has something to do with your python environment. You may want to create an independent python environment for pylipid so that other packages do not mess up with the installed libraries.
