### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by BDehury85** [wlsong/PyLipID#2]
I am trying to run PyLipID for my membrane (POPC) trajectory containing 1500 snapshots:
 I am getting following error:

python pylipid.py -f ../md.xtc -c ../md.gro -cutoffs 0.55 1.4 -lipids POPC -lipid_atoms C13 C14 C15 N C12 C11 O12 P O13 O14 O11 -nprot 1 -resi_offset 5 -save_dataset -pdb XXXX.pdb -chain A
Traceback (most recent call last):
  File "pylipid.py", line 970, in <module>
    for item in args.resi_list:
TypeError: 'NoneType' object is not iterable

**Comment by wlsong** [comment]
Hi, the error was coming from an update issue. I've corrected along with the readme page. Please let me know if there are other issues. Wanling

**Comment by BDehury85** [comment]
python pylipid.py -f ../md.xtc -c ../md.gro -cutoffs 0.55 1.4 -lipids POPC -lipid_atoms C13 C14 C15 N C12 C12 O11 P O13 O14 O11 -nprot 1 -resi_offset 5 -save_dataset -pdb BD.pdb -chain A -pymol_gui False
Traceback (most recent call last):
  File "pylipid.py", line 970, in <module>
    for item in args.resi_list:
TypeError: 'NoneType' object is not iterable

**Comment by wlsong** [comment]
Hi,
The error should be fixed now. Please download the latest script :)
Wanling
