### ISSUE TITLE
PyLipID tutorial

### ISSUE THREAD

**Issue by andresilvapimentel** [wlsong/PyLipID#20]
I am sorry but you closed the issue before I could solve it. Just remembering the issue:

Question: Could you please let me know how you installed pylipid? If you installed pylipid via 'pip install pylipid', it shouldn't have an issue.

Answer: I installed it using pip install pylipid and it worked at the first day I used. Then, in the following day, it stopped working in a very strange manner.

Question: Do you think this is relevant to the issue you reported here? https://stackoverflow.com/questions/53017174/attributeerror-module-networkx-algorithms-community-has-no-attribute-best-pa

I tried to install this module, but it did not work it. Could you help me, please?

Question: If you have install pylipid properly, you should be able to go through the tutorials step by step, or run all of the analysis once via the script provided in 'Demo' (https://pylipid.readthedocs.io/en/master/demo.html)

I also tried to use the script by google colab and by python console. I worked in the python console but not in google colab as well.

I got the error message in the command node_list, modularity = li.compute_binding_nodes(threshold=4, print_data=False)

  86                                    # negative correlationsare are forced to separate to different binding sites.
     87     graph = nx.Graph(corrcoef)
---> 88     partition = community.best_partition(graph, weight='weight')
     89     values = [partition.get(node) for node in graph.nodes()]
     90     node_list = []

AttributeError: module 'community' has no attribute 'best_partition'

Could you help me, please?

**Comment by andresilvapimentel** [comment]
Comment: I don't understand why 'worked at the first day' then stopped working.
It may has something to do with your python environment. You may want to create an independent python environment for pylipid so that other packages do not mess up with the installed libraries.

I also did not understand it. How can I create an independent python environment for pylipid so that other packages do not mess up with the installed libraries?

**Comment by wlsong** [comment]
Hi,

I think the easiest way to test this is to uninstall your pylipid and then reinstall it. It seems that some of you python libraries have messed up. 
I don't know what your python environment is like, so it's difficult for me say what you should do. If you are using conda to setup your python environment, you can use 'conda env create' to create an independent python environment. If you are not using conda, I recommend you switch to use it as it makes managing your libraries easy.
