### ISSUE TITLE
Jobs getting killed

### ISSUE THREAD

**Issue by BDehury85** [wlsong/PyLipID#3]
python pylipid.py -f md.xtc -c md.gro -cutoffs 0.35 0.55 -lipids DPPC -lipid_atoms C13 C14 C15 O12 P O13 O14 O11 -nprot 1 -save_dataset -pdb 1.pdb -pymol_gui False

Creating new director: /Data/Backup/Interaction_DPPC

########## md.xtc 

Killed

**Comment by wlsong** [comment]
Could you provide more information regarding the error? 
Could it be a memory error? In that case, you could try the flag -stride to analyse less amount of frames. But unless your trajectory is huge, this shouldn't be a problem..
